# # # # # # # # # # # # #
#  M y r o n - B l o g  #
# # # # # # # # # # # # #

# Basic
name:               "Myron"



author:
  name:             黄穆斌
  facebook:         your-id
  twitter:          your-id
  github:           huangmubin
  linkedin:         your-id
  medium:           your-id
  tumblr:           your-id
  email:            hmb87381041@iCloud.com

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "your-id"

# URL
url:                "https://huangmubin.github.io"
#url:               "localhost:4000"
baseurl:            "https://huangmubin.github.io"


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/huangmubin"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         "https://huangmubin.github.io"
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         "https://huangmubin.github.io"
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
